version: "3"
services:
  phoenix:
    container_name: imgur_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PG_USERNAME: postgres
      PG_PASSWORD: postgres
      PG_HOST: imgur-postgres
    env_file: .dev.env
    command: iex -S mix phx.server
    ports:
      - "8000:4000"
    volumes:
      - .:/app
    links:
      - imgur-postgres
    depends_on:
      - imgur-postgres
    networks:
      shared_network:
        aliases:
          - imgur-host
      default: 
        aliases:
          - imgur-host
    restart: always

  imgur-postgres:
    image: postgres:9.6.5-alpine
    container_name: imgur-postgres
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imgur_global_db
      PGDATA: /data/pgdata
    volumes:
      - ./data:/data:cached

  imgur-rabbitmq:
    image: rabbitmq:3.7.5-management
    container_name: imgur-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: v1
    ports:
      - 5677:5672
      - 15677:15672
    networks:
      - shared_network
      - default

networks:
  shared_network:
    external:
      name: imgur_network
